[project]
name = "diary"
version = "1.0.0"
description = "Diary Flet app"
requires-python = ">=3.11"
dependencies = [
    "flet>=0.82.0",
    "flet-stt>=0.1.5",
    "dateparser>=1.2.0",
    "supabase>=2.0.0",
    "python-dotenv>=1.0.1",
]

[tool.flet.android.permission]
"android.permission.INTERNET" = true
"android.permission.RECORD_AUDIO" = true

[tool.flet.app]
exclude = ["flet_stt"]
